version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    tmpfs:
      - /app/files
    environment:
      - KEY=DontChangeMeOrTheChallengeWillBreak
      - FLAG=flag{FIRST_ZIP_OR_LAST_ZIP}
      - PYTHONUNBUFFERED=TRUE
